export const INVENTORY_POST_REQUEST =  'INVENTORY_POST_REQUEST'
export const INVENTORY_POST_SUCCESS =  'INVENTORY_POST_SUCCESS'
export const INVENTORY_POST_FAIL =  'INVENTORY_POST_FAIL'

export const TRANSACTION_RECORD_REQUEST =  'TRANSACTION_RECORD_REQUEST'
export const TRANSACTION_RECORD_SUCCESS =  'TRANSACTION_RECORD_SUCCESS'
export const TRANSACTION_RECORD_FAIL =  'TRANSACTION_RECORD_FAIL'

export const TOP_PRODUCT_REQUEST =  'TOP_PRODUCT_REQUEST'
export const TOP_PRODUCT_SUCCESS =  'TOP_PRODUCT_SUCCESS'
export const TOP_PRODUCT_FAIL =  'TOP_PRODUCT_FAIL'